// <auto-generated />
using BackendProject.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BackendProject.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260907063820_RelationalSchema")]
    partial class RelationalSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BackendProject.Models.Packing", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Size")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("Weight")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("Size");

                    b.ToTable("Packings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Size = "1-Quart",
                            Weight = 1.1m
                        },
                        new
                        {
                            Id = 2,
                            Size = "1-Gallon",
                            Weight = 4.5m
                        },
                        new
                        {
                            Id = 3,
                            Size = "2-Gallon",
                            Weight = 9.0m
                        },
                        new
                        {
                            Id = 4,
                            Size = "5-Gallon",
                            Weight = 22.5m
                        },
                        new
                        {
                            Id = 5,
                            Size = "500ml Can",
                            Weight = 0.6m
                        },
                        new
                        {
                            Id = 6,
                            Size = "20L Drum",
                            Weight = 90.0m
                        });
                });

            modelBuilder.Entity("BackendProject.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("Discount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Category");

                    b.HasIndex("Title");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("BackendProject.Models.ProductPacking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PackingId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PackingId");

                    b.HasIndex("ProductId", "PackingId")
                        .IsUnique();

                    b.ToTable("ProductPackings");
                });

            modelBuilder.Entity("BackendProject.Models.ProductShade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("ShadeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ShadeId");

                    b.HasIndex("ProductId", "ShadeId")
                        .IsUnique();

                    b.ToTable("ProductShades");
                });

            modelBuilder.Entity("BackendProject.Models.Shade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ColorCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShadeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ShadeName");

                    b.ToTable("Shades");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ColorCode = "#0B6E4F",
                            ShadeName = "Emerald Green"
                        },
                        new
                        {
                            Id = 2,
                            ColorCode = "#1A1A1A",
                            ShadeName = "Matte Black"
                        },
                        new
                        {
                            Id = 3,
                            ColorCode = "#F7F3E9",
                            ShadeName = "Ivory White"
                        },
                        new
                        {
                            Id = 4,
                            ColorCode = "#1B4FA0",
                            ShadeName = "Cobalt Blue"
                        },
                        new
                        {
                            Id = 5,
                            ColorCode = "#B4552C",
                            ShadeName = "Terracotta"
                        },
                        new
                        {
                            Id = 6,
                            ColorCode = "#5A6570",
                            ShadeName = "Slate Grey"
                        },
                        new
                        {
                            Id = 7,
                            ColorCode = "#E8B531",
                            ShadeName = "Sunflower"
                        },
                        new
                        {
                            Id = 8,
                            ColorCode = "#D9899A",
                            ShadeName = "Rose Blush"
                        });
                });

            modelBuilder.Entity("BackendProject.Models.ProductPacking", b =>
                {
                    b.HasOne("BackendProject.Models.Packing", "Packing")
                        .WithMany("ProductPackings")
                        .HasForeignKey("PackingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackendProject.Models.Product", "Product")
                        .WithMany("ProductPackings")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Packing");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("BackendProject.Models.ProductShade", b =>
                {
                    b.HasOne("BackendProject.Models.Product", "Product")
                        .WithMany("ProductShades")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackendProject.Models.Shade", "Shade")
                        .WithMany("ProductShades")
                        .HasForeignKey("ShadeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Shade");
                });

            modelBuilder.Entity("BackendProject.Models.Packing", b =>
                {
                    b.Navigation("ProductPackings");
                });

            modelBuilder.Entity("BackendProject.Models.Product", b =>
                {
                    b.Navigation("ProductPackings");

                    b.Navigation("ProductShades");
                });

            modelBuilder.Entity("BackendProject.Models.Shade", b =>
                {
                    b.Navigation("ProductShades");
                });
#pragma warning restore 612, 618
        }
    }
}
